services:
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - 27017:27017

    common:
        container_name: common
        image: common
        environment:
            PORT: 80
            MONGO: mongo
        ports:
            - 80:80
        depends_on:
            - mongo
